#!/usr/bin/env bash
# provision.sh
# ------------
# Runs INSIDE the freshly-created calautox app LXC. Installs Docker, clones
# the repo, writes deploy/.env, and starts the compose stack.
#
# Normally invoked by ../setup-app-lxc.sh via `pct push` + `pct exec`. All
# inputs come from env vars — there is no interactive prompting here.
#
# Required env:
#   AUTOX_DB_HOST        DB host/IP (no default — caller must set)
#   AUTOX_DB_PASSWORD    API DB password
#
# Optional env (with defaults):
#   CALAUTOX_REPO_URL    default: https://github.com/juancstlm/calautox.git
#   CALAUTOX_REPO_REF    default: main
#   DEPLOY_USER          default: deploy
#   CALAUTOX_HOME        default: /home/${DEPLOY_USER}/calautox
#   AUTOX_DB_PORT        default: 5432
#   AUTOX_DB_NAME        default: autox
#   AUTOX_DB_USER        default: autox_api
#   API_LISTEN           default: :8080
#
# Flags:
#   --force-env          overwrite deploy/.env even if it already exists
#   --skip-up            install everything but don't run `docker compose up`

set -euo pipefail

CALAUTOX_REPO_URL="${CALAUTOX_REPO_URL:-https://github.com/juancstlm/calautox.git}"
CALAUTOX_REPO_REF="${CALAUTOX_REPO_REF:-main}"
DEPLOY_USER="${DEPLOY_USER:-deploy}"
CALAUTOX_HOME="${CALAUTOX_HOME:-/home/${DEPLOY_USER}/calautox}"

AUTOX_DB_PORT="${AUTOX_DB_PORT:-5432}"
AUTOX_DB_NAME="${AUTOX_DB_NAME:-autox}"
AUTOX_DB_USER="${AUTOX_DB_USER:-autox_api}"
API_LISTEN="${API_LISTEN:-:8080}"

FORCE_ENV=0
SKIP_UP=0
for arg in "$@"; do
    case "$arg" in
        --force-env) FORCE_ENV=1 ;;
        --skip-up)   SKIP_UP=1 ;;
        -h|--help)   sed -n '2,30p' "$0"; exit 0 ;;
        *) echo "unknown flag: $arg" >&2; exit 2 ;;
    esac
done

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "must run as root"
[ -f /etc/debian_version ] || die "expected Debian 12 (this is not a Debian system)"
[ -n "${AUTOX_DB_HOST:-}" ]     || die "AUTOX_DB_HOST must be set"
[ -n "${AUTOX_DB_PASSWORD:-}" ] || die "AUTOX_DB_PASSWORD must be set"

# ---------- 1. apt + base packages --------------------------------------------

log "updating apt and installing base packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y --no-install-recommends \
    ca-certificates curl git gnupg lsb-release sudo

# ---------- 2. docker engine + compose plugin ---------------------------------

if ! command -v docker >/dev/null 2>&1; then
    log "installing Docker Engine + compose plugin"
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    codename="$(. /etc/os-release && echo "$VERSION_CODENAME")"
    cat > /etc/apt/sources.list.d/docker.list <<EOF
deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian ${codename} stable
EOF
    apt-get update -qq
    apt-get install -y --no-install-recommends \
        docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    systemctl enable --now docker
else
    log "Docker already installed: $(docker --version)"
fi

# ---------- 3. deploy user ----------------------------------------------------

if ! id "${DEPLOY_USER}" >/dev/null 2>&1; then
    log "creating user ${DEPLOY_USER}"
    useradd --create-home --shell /bin/bash "${DEPLOY_USER}"
fi
usermod -aG docker "${DEPLOY_USER}"

# ---------- 4. clone or update the repo ---------------------------------------

if [ -d "${CALAUTOX_HOME}/.git" ]; then
    log "repo already cloned at ${CALAUTOX_HOME}; fetching ${CALAUTOX_REPO_REF}"
    sudo -u "${DEPLOY_USER}" git -C "${CALAUTOX_HOME}" fetch --depth 1 origin "${CALAUTOX_REPO_REF}"
    sudo -u "${DEPLOY_USER}" git -C "${CALAUTOX_HOME}" checkout "${CALAUTOX_REPO_REF}"
    sudo -u "${DEPLOY_USER}" git -C "${CALAUTOX_HOME}" reset --hard "origin/${CALAUTOX_REPO_REF}" || true
else
    log "cloning ${CALAUTOX_REPO_URL} (${CALAUTOX_REPO_REF}) into ${CALAUTOX_HOME}"
    install -d -o "${DEPLOY_USER}" -g "${DEPLOY_USER}" "$(dirname "${CALAUTOX_HOME}")"
    sudo -u "${DEPLOY_USER}" git clone --depth 1 --branch "${CALAUTOX_REPO_REF}" \
        "${CALAUTOX_REPO_URL}" "${CALAUTOX_HOME}"
fi

ENV_PATH="${CALAUTOX_HOME}/deploy/.env"

# ---------- 5. write deploy/.env ----------------------------------------------

if [ -f "${ENV_PATH}" ] && [ "${FORCE_ENV}" -ne 1 ]; then
    log "${ENV_PATH} already exists — skipping (pass --force-env to overwrite)"
else
    log "writing ${ENV_PATH}"
    install -d -o "${DEPLOY_USER}" -g "${DEPLOY_USER}" "$(dirname "${ENV_PATH}")"
    umask 077
    cat > "${ENV_PATH}" <<EOF
# Generated by proxmox-scripts/calautox/provision.sh
AUTOX_DB_HOST=${AUTOX_DB_HOST}
AUTOX_DB_PORT=${AUTOX_DB_PORT}
AUTOX_DB_NAME=${AUTOX_DB_NAME}
AUTOX_DB_USER=${AUTOX_DB_USER}
AUTOX_DB_PASSWORD=${AUTOX_DB_PASSWORD}

API_LISTEN=${API_LISTEN}
EOF
    chown "${DEPLOY_USER}:${DEPLOY_USER}" "${ENV_PATH}"
    chmod 600 "${ENV_PATH}"
fi

# ---------- 6. build + start the stack ----------------------------------------

if [ "${SKIP_UP}" -eq 1 ]; then
    log "--skip-up set; not running docker compose"
    log "to start the stack manually:"
    log "  sudo -u ${DEPLOY_USER} -- bash -lc 'cd ${CALAUTOX_HOME}/deploy && docker compose up -d --build'"
    exit 0
fi

log "building and starting the compose stack"
sudo -u "${DEPLOY_USER}" -- bash -lc \
    "cd '${CALAUTOX_HOME}/deploy' && docker compose up -d --build"

log "done — container status:"
sudo -u "${DEPLOY_USER}" -- bash -lc \
    "cd '${CALAUTOX_HOME}/deploy' && docker compose ps"
